### 函数的基本特点

Go函数不支持嵌套、重载和默认参数

但支持下面的特性：

无需声明原型、不定长度变参、多返回值、命名返回值参数、匿名函数、闭包

定义函数使用关键字func,而且左大括号不能另起一行，**函数也可以作为一种类型使用**

```
func main(){
	//函数也是个类型
	a := A
	a()
	
	//匿名函数
	b := func(){
		fmt.Println("Func A")
	}
	b()
}

func A(){
	fmt.Println("Func A")
}
```

### 函数的值传递与引用传递

对于切片来说永远是引用传递，但是如果把切片直接传到函数中会创建一个新的切片

**传切片**：

```
func main(){

	slice:=[]int{1,2,3}
	fmt.Printf("slice %v,slice address %p\n",slice,&slice)
	slice=changeSlice(slice)
	fmt.Printf("slice %v,slice address %p\n",slice,&slice)
}
func changeSlice(nums []int)[]int{
	fmt.Printf("nums: %v,nums addr: %p\n",nums,&nums)
	nums[1]=111
	return nums

}
//
//slice [1 2 3],slice address 0xc04204a3a0
//nums: [1 2 3],nums addr: 0xc04204a400
//slice [1 111 3],slice address 0xc04204a3a0
```



**传切片的指针**：

```
func main(){
	slice:=[]int{1,2,3}
	fmt.Printf("slice %v,slice address %p\n",slice,&slice)
	slice=changeSlice(&slice)
	fmt.Printf("slice %v,slice address %p\n",slice,slice)
}

//将切片的指针传给函数

func changeSlice(nums *[]int)[]int{
	fmt.Printf("nums: %v,nums addr: %p\n",*nums,&nums)
	
	//如果写成*nums[1]会报错，只能写成(*nums)[1]
	
	(*nums)[1]=111
	return *nums
}
//打印结果
slice [1 2 3],slice address 0xc0000a6020
nums: [1 2 3],nums addr: 0xc0000ae020
slice [1 111 3],slice address 0xc0000b6020

```





### 闭包

```
func main(){
	f := closure(10)
	fmt.Println(f(1))
	fmt.Println(f(2))
}

func closure(x int) func(int) int{
	//返回值中的x从外层函数中获得
	return func(y int) int{
		fmt.Printf("%p\n",&x)
		return x + y
	}
}
//打印结果为：
// 0xc000016080
// 11
// 0xc000016080
// 12
// 可以看到变量x始终是同一个变量
```



### 析构函数defer

- defer的执行方式类似于其他语言中的析构函数，在函数体执行结束后按照调用顺序的相反顺序逐个执行

  ```
  func main(){
  // 先打印b后打印a
  	 defer fmt.Println("a")
  	 defer fmt.Println("b")
  }
  ```

  ```
  func main(){
  	for i:=0;i<3;i++{
  	
  		//下面的写法等同于
  		// a := func(){fmt.Println(i)}
  		//defer a()
  		
  		defer func(){
  			fmt.Println(i)
  		}()
  	}
  }
  //打印结果是
  3
  3
  3
  这是因为在退出时执行defer,而此时i的值为3
  ```

  

- 即使函数发生严重错误也会执行

  go没有try catch, 使用panic recover机制来处理错误，而revcover只有在存在defer的函数中有效

  注意使用defer函数来recover必须把defer放在panic前面，因为一旦panic就会停止

  ```
  func main()  {
  	defer func() {
  		if err := recover();err !=nil{
  			fmt.Printf("Recovered!")
  		}
  	}()
  	A()
  	B()
  	C()
  
  }
  func A(){
  	fmt.Println("Func A")
  }
  func B(){
  	panic("I am finished")
  }
  func C(){
  	fmt.Println("Func C")
  }
  
  //打印结果
  Func A
  Recovered!
  
  ```

  

  - 支持匿名函数的调用

  - 常用于资源清理、文件关闭、解锁以及记录时间等操作

  - 通过与匿名函数配合可以在return之后修改函数计算结果

  - 如果函数体内某个变量作为defer时匿名函数的参数，则在定义defer时即已经获得了拷贝，否则则是引用某个变量的地址

  - go没有异常机制，但有panic/recover模式来处理错误

  - panic可以在任何地方引发，但recover只有在defer调用的函数中有效

    

  例子

  ```
  func main()  {
  	var fs = [4]func(){
  
  	}
  	for i := 0;i < 4; i++{
  		//没有用到匿名函数或者闭包，i只是一个普通的参数
  		defer fmt.Println("defer i = \n",i)
  		//匿名函数并没有i这个参数，所以这里用到了闭包，i是从上一层函数中得到的。
  		//由于函数结束后i=4,闭包获取到的数字就是4
  		defer func(){
  			fmt.Println("defer_closure i= \n",i)
  		}()
  		//匿名函数并没有i这个参数，所以这里用到了闭包，i是从上一层函数中得到的。
  		//由于函数结束后i=4,闭包获取到的数字就是4
  		fs[i] = func(){
  			fmt.Println("closure i = \n",i)
  		}
  	}
  	for _,f := range fs{
  		f()
  	}
  }
  
  //打印结果为
  closure i = 4
  closure i = 4
  closure i = 4
  closure i = 4
  defer_closure i= 4
  defer i = 3
  defer_closure i= 4
  defer i = 2
  defer_closure i= 4
  defer i = 1
  defer_closure i= 4
  defer i = 0
  
  ```

  